apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-keyvault-secret-provider
  namespace: development
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    keyvaultName: "<mi-keyvault>"
    tenantId: "<mi-tenant-id>"
    objects: |
      array:
        - |
          objectName: "clientidcodeauthorization"
          objectType: secret
        - |
          objectName: "clientsecretcodeauthorization"
          objectType: secret
        - |
          objectName: "clientidclientcredentials"
          objectType: secret
       - |
          objectName: "clientsecretclientcredentials"
          objectType: secret
       - |
          objectName: "postgresuser"
          objectType: secret
       - |
          objectName: "postgrespassword"
          objectType: secret
      - |
          objectName: "mongoinitdbrootusername"
          objectType: secret
      - |
          objectName: "mongoinitdbrootpassword"
          objectType: secret
      - |
          objectName: "connectionsendnotificationpost"
          objectType: secret  
      - |
          objectName: "keysecret"
          objectType: secret  


  secretObjects: # ðŸ‘ˆ Esto sincroniza los valores con Kubernetes Secrets
    - secretName: authorization-secrets
      type: Opaque
      data:
        - objectName: "CLIENT_ID_CODE_AUTHORIZATION"
          key: "CLIENT_ID_CODE_AUTHORIZATION"
        - objectName: "CLIENT_SECRET_CODE_AUTHORIZATION"
          key: "CLIENT_SECRET_CODE_AUTHORIZATION"
        - objectName: "CLIENT_ID_CLIENT_CREDENTIALS"
          key: "CLIENT_ID_CLIENT_CREDENTIALS"
        - objectName: "CLIENT_SECRET_CLIENT_CREDENTIALS"
          key: "CLIENT_SECRET_CLIENT_CREDENTIALS"
    - secretName: postgres-secrets
      type: Opaque
      data:
        - objectName: "POSTGRES_USER"
          key: "POSTGRES_USER"
        - objectName: "POSTGRES_PASSWORD"
          key: "POSTGRES_PASSWORD"
    - secretName: mongo-secrets
      type: Opaque
      data:
        - objectName: "MONGO_INITDB_ROOT_USERNAME"
          key: "MONGO_INITDB_ROOT_USERNAME"
        - objectName: "MONGO_INITDB_ROOT_PASSWORD"
          key: "MONGO_INITDB_ROOT_PASSWORD"
    - secretName: gateway-secrets
      type: Opaque
      data:
        - objectName: "KEY_SECRET"
          key: "KEY_SECRET"
    - secretName: posts-secrets
      type: Opaque
      data:
        - objectName: "CONNECTION_SEND_NOTIFICATION_POST"
          key: "CONNECTION_SEND_NOTIFICATION_POST"
