apiVersion: v1
kind: Service
metadata:
  name: gateway-server-dev
spec:
  ports:
    - port: 8090
      protocol: TCP
      targetPort: 8090
  selector:
    app: gateway-server-dev
  type: LoadBalancer
  # ClusterIP => PARA COMUNICACION DENTROD DEL CLUSTER
  # NODEPORT => PARA EXPONER UN SERVICIO MEDIANTE UN PUERTO DEL CLUSTER
  # LOADBALANCER => EXPONE O TE ORTORGA UNA IP EXTERNA MEDIANTE LA CUAL TE PUEDAS COMUNICAR
